import time
import uuid

import Adafruit_BluefruitLE

SERVICE_UUIDS = [
    uuid.UUID('0000180f-0000-1000-8000-00805f9b34fb'),  # Battery
    uuid.UUID('f29b1525-cb19-40f3-be5c-7241ecb82fd2'),  # Sensors
    uuid.UUID('f29b1523-cb19-40f3-be5c-7241ecb82fd1')  # LED Matrix
]

CHARACTERISTIC_UUIDS = {
    uuid.UUID('00002a19-0000-1000-8000-00805f9b34fb'),  # BATTERY 
    uuid.UUID('f29b1529-cb19-40f3-be5c-7241ecb82fd2'),  # BUTTON
    uuid.UUID('f29b1528-cb19-40f3-be5c-7241ecb82fd2'),  # ROTATION
    uuid.UUID('f29b1527-cb19-40f3-be5c-7241ecb82fd2'),  # SWIPE
    uuid.UUID('f29b1526-cb19-40f3-be5c-7241ecb82fd2'),  # FLY
    uuid.UUID('f29b152D-cb19-40f3-be5c-7241ecb82fd2'),  # ACCELEROMETER
    uuid.UUID('f29b1524-cb19-40f3-be5c-7241ecb82fd1')  # LED_MATRIX
}

# Get the BLE provider for the current platform.
ble = Adafruit_BluefruitLE.get_provider()

def main():
    # Clear previously received data from the controller/adapter
    ble.clear_cached_data()

    # Connect to the default or first adapter and start scan
    adapter = ble.get_default_adapter()
    adapter.power_on()
    print('Using : {0}'.format(adapter.name))
    ble.disconnect_devices(SERVICE_UUIDS)
    adapter.start_scan()

    # It needs bit of time to scan the devices. Some Peripherals advertise in different
    time.sleep(5)

    # Find all the ble devices with the name nuimo,this filtering part is done by Adafruit
    # devices -> interfaces/device/bluez-device, properties and method can be found there
    # id is MAC on Linux and on OSX uuid generated by OSX
    devices = ble.find_devices(service_uuids=[SERVICE_UUIDS[2]])

    for device in devices:
        print('Found device: {0}, id: {1}'.format(device.name, device.id))        
        if device.id == uuid.UUID('88ac52af-993c-418e-aa6e-31cf61c29cfd'):            
            print 'Found myNuimo'
            nuimo = device

            # Once myNuimo is found, then stop scanning
            adapter.stop_scan()

            nuimo.connect()
            print 'Connected to myNuimo'

            nuimo.discover(SERVICE_UUIDS, CHARACTERISTIC_UUIDS)
            print 'Discovery Mode'
            
            print 'Discovered Characteristics'
            led_matrix_service = nuimo.find_service(SERVICE_UUIDS[2])
            led_matrix_characteristic = led_matrix_service.list_characteristics()[0]            
            sensor_service = nuimo.find_service(SERVICE_UUIDS[1])
            sensor_characteristics = sensor_service.list_characteristics()
            for sensor_characteristic in sensor_characteristics:
                print sensor_characteristic.uuid

            button_characteristic = sensor_characteristics[0]
            rotation_characteristic = sensor_characteristics[3]
            accelerometer_characteristic = sensor_characteristics[7]
            
            def button_received(data):
                print 'Button: ', map(ord, data)

            def rotation_received(data):
                print 'Encoder: ', map(ord, data)

            def accelerometer_received(data):
                print 'Orientation: ', map(ord, data)

            button_characteristic.start_notify(button_received)
            rotation_characteristic.start_notify(rotation_received)
            accelerometer_characteristic.start_notify(accelerometer_received)

            while True:
                pass

    adapter.power_off()
    print 'Disconnected from myNuimo'

ble.initialize()
ble.run_mainloop_with(main)
